app:
  port: 8000  #服务端口
  apkPath: /Users/xiaobai/Downloads/VlinkVPN_Android.apk #需要处理的apk路径
  updateConfig:
    replacePackageNameEnable: false  #是否启动更换包名 如不启动将只会自动换签名
    interval: 20                     #更换周期单位秒 如设置0 默认60
log:
  file: temp/log       #日志目录
  level: info          #trace debug info warning error fatal panic  日志级别
  colour: true         #日志控制台是否显示不同颜色


#apk下载地址
# walle渠道包    域名/guide/channel/download/渠道id/apk名称.apk
# 非渠道包       域名/guide/download/apk名称.apk
