uuids:
    官方频道: "{\"channelId\":52}"
    破解群广告: "{\"channelId\":51}"
    破解VPN软件机场: "{\"channelId\":54}"
input:  /Volumes/DATA/Sourcetree/VlinkVPN_Client/build/app/outputs/flutter-apk/app-release.apk
appName: VlinkVPN
